services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "5100-5102:3002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 3